CREATE TABLE IF NOT EXISTS Comments(commentId BIGINT PRIMARY KEY NOT NULL, uid BIGINT NOT NULL, parentId BIGINT NOT NULL, postId BIGINT NOT NULL, content TEXT NOT NULL, creationTime BIGINT NOT NULL);
